character:
    name: Destruction Warlock
    level: 60
pet:
    summon: imp
stats:
    intellect: 0
    spell_power: 700
    crit_percent: 11.2
    haste_percent: 8
    spirit: 177
    hit_percent: 14
    max_mana: 6000
target:
    type: equal_level
    level: 60
rotation: destruction-cataclysmic.yaml
simulation:
    duration_seconds: 300
    iterations: 5000
mystic_enchants:
    limits:
        legendary: 1
        epic: 3
        rare: 6
    equipped:
        legendary:
            - cataclysmic_burst
        epic:
            - agent_of_chaos
            - guldans_chosen
            - heating_up
        rare:
            - demonic_aegis
            - glyph_of_chaos_bolt
            - glyph_of_conflagrate
            - glyph_of_life_tap
            - suppression
