character:
    name: Destruction Warlock
    level: 60
pet:
    summon: imp
stats:
    intellect: 0
    spell_power: 863
    crit_percent: 14.95
    haste_percent: 8.8
    spirit: 300
    hit_percent: 14
    max_mana: 6000
target:
    type: equal_level
    level: 60
    debuffs:
        curse_of_elements: true
rotation: destruction-cataclysmic.yaml
simulation:
    duration_seconds: 300
    iterations: 5000
mystic_enchants:
    limits:
        legendary: 1
        epic: 3
        rare: 6
    equipped:
        legendary:
            - cataclysmic_burst
        epic:
            - agent_of_chaos
            - guldans_chosen
            - heating_up
        rare:
            - demonic_aegis
            - glyph_of_chaos_bolt
            - glyph_of_conflagrate
            - glyph_of_immolate
            - glyph_of_life_tap
            - suppression
